(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SUITS=['♠','♥','♦','♣'], RED=['♥','♦'], RANKS=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const KEY='adams-solitaire-v1', pref=JSON.parse(localStorage.getItem(KEY)||'{}');
const settings=Object.assign({name:'',theme:'green',sound:true,dropTargets:false,scores:{}},pref.settings||{});
let state=pref.active||null, undo=[], timerId, setupGame='klondike', setupVariant='draw1', setupDifficulty='standard', selected=null, drag=null, zoomTimer=null, suppressCardClick=false;
const names={klondike:'Klondike',freecell:'FreeCell',spider:'Spider'};

function save(){localStorage.setItem(KEY,JSON.stringify({settings,active:state}));}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
function fmt(n){return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function shuffle(a,seed=Math.random()*1e9){let r=mulberry(seed|0);for(let i=a.length-1;i;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function mulberry(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function deck(decks=1,suits=SUITS){let a=[],id=0;for(let d=0;d<decks;d++)for(let s of suits)for(let r=1;r<=13;r++)a.push({id:`${Date.now()}-${id++}`,s,r,up:false});return a}
function clone(o){return JSON.parse(JSON.stringify(o))}
function label(c){return `${RANKS[c.r-1]}${c.s}`}
function recordUndo(){undo.push(clone(state));if(undo.length>100)undo.shift()}
function modeKey(){return `${state.type}-${state.variant}-${state.difficulty}`}
function beginClock(){clearInterval(timerId);timerId=setInterval(()=>{if(state&&!state.won){state.time++;$('#timer').textContent=fmt(state.time);if(state.time%5===0)save()}},1000)}
function sound(kind='move'){if(!settings.sound)return;try{let ac=sound.ac||(sound.ac=new(window.AudioContext||webkitAudioContext)()),o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.type='sine';o.frequency.value=kind==='win'?660:kind==='flip'?360:240;g.gain.setValueAtTime(.035,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.09);o.start();o.stop(ac.currentTime+.1)}catch(e){}}

function welcome(){clearInterval(timerId);show('welcome');document.body.dataset.theme=settings.theme;$('#greeting').textContent=settings.name?`Welcome back, ${settings.name}`:'Welcome — choose your game';let r=$('#resumeCard');if(state&&!state.won){r.classList.remove('hidden');$('#resumeTitle').textContent=names[state.type];$('#resumeMeta').textContent=`${state.difficulty.toUpperCase()} · ${fmt(state.time)}`}else r.classList.add('hidden')}
function setup(type){setupGame=type;setupVariant=type==='klondike'?'draw1':type==='spider'?'1suit':'classic';setupDifficulty=type==='spider'?'easy':'standard';$('#setupTitle').textContent=names[type];let variants=type==='klondike'?[['draw1','Draw 1'],['draw3','Draw 3']]:[['classic','Classic']];$('#variantGroup').classList.toggle('hidden',type!=='klondike');$('#variantOptions').innerHTML=variants.map(([v,l])=>`<button data-v="${v}" class="${v===setupVariant?'selected':''}">${l}</button>`).join('');$('#difficultyOptions').closest('.setting-group').classList.toggle('hidden',type!=='spider');let ds=[['easy','Easy','One suit · Random deal'],['standard','Standard','Two suits · Random deal'],['hard','Hard','Four suits · Random deal']];$('#difficultyOptions').innerHTML=ds.map(([v,l,d])=>`<button data-d="${v}" class="${v===setupDifficulty?'selected':''}"><b>${l}</b><small>${d}</small></button>`).join('');show('setup')}

function newState(){let seed=setupDifficulty==='hard'?Math.random()*1e9:dailySeed(`${setupGame}-${setupVariant}-${setupDifficulty}-${Math.random()}`);let s={type:setupGame,variant:setupVariant,difficulty:setupDifficulty,seed,time:0,moves:0,score:setupGame==='spider'?500:0,won:false,started:Date.now()};if(setupGame==='klondike')dealKlondike(s);if(setupGame==='freecell')dealFreecell(s);if(setupGame==='spider')dealSpider(s);state=s;undo=[];selected=null;save();play();}
function dailySeed(x){let n=2166136261;for(let c of x)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0}
function dealKlondike(s){let d=shuffle(deck(),s.seed);s.tableau=Array.from({length:7},()=>[]);for(let col=0;col<7;col++)for(let row=0;row<=col;row++){let c=d.pop();c.up=row===col;s.tableau[col].push(c)}s.stock=d;s.waste=[];s.foundations=[[],[],[],[]];s.redeals=0}
function dealFreecell(s){let d=shuffle(deck(),s.seed);s.tableau=Array.from({length:8},()=>[]);d.forEach((c,i)=>{c.up=true;s.tableau[i%8].push(c)});s.cells=[null,null,null,null];s.foundations=[[],[],[],[]]}
function dealSpider(s){let suits=s.variant==='1suit'?['♠']:s.variant==='2suit'?['♠','♥']:SUITS;let d=shuffle(deck(8/suits.length,suits),s.seed);s.tableau=Array.from({length:10},()=>[]);for(let i=0;i<54;i++){let c=d.pop();c.up=i>=44;s.tableau[i%10].push(c)}s.stock=d;s.completed=0}

function play(){show('game');document.body.dataset.game=state.type;$('#gameTitle').textContent=names[state.type];$('#gameMode').textContent=`${state.variant.replace('draw','DRAW ').replace('suit',' SUIT').toUpperCase()} · ${state.difficulty.toUpperCase()}`;$('#score').textContent=state.score;$('#timer').textContent=fmt(state.time);$('#soundBtn').textContent=settings.sound?'♪':'♩';render();beginClock()}
function pos(i,n,gap){return `calc(${i} * ((100% - ${n} * var(--card-w)) / ${Math.max(1,n-1)} + var(--card-w)))`}
function compactBoard(){return matchMedia('(orientation:landscape) and (max-height:600px)').matches}
function pileHTML(kind,index,left,top,suit=''){return `<div class="pile ${kind}" data-kind="${kind}" data-index="${index}" data-suit="${suit}" style="left:${left};top:${top}"></div>`}
function cardHTML(c,kind,pile,i,left,top,z){return `<div class="card ${c.up?'':'down'} ${RED.includes(c.s)?'red':''}" data-id="${c.id}" data-kind="${kind}" data-pile="${pile}" data-index="${i}" style="left:${left};top:${top};z-index:${z}"><span class="corner"><span>${RANKS[c.r-1]}</span><span class="suit">${c.s}</span></span><span class="center-suit">${c.s}</span></div>`}
function render(options={}){
  if(!state)return;
  let before=new Map($$('.card').map(el=>[el.dataset.id,el.getBoundingClientRect()]));
  selected=null;
  let b=$('#board'),h='';
  if(state.type==='klondike')h=renderK();
  if(state.type==='freecell')h=renderF();
  if(state.type==='spider')h=renderS();
  b.innerHTML=h;bindCards();
  let preview=options.dragPreview,groupIds=new Set(preview?.originals.map(el=>el.dataset.id)||[]),newCards=[];
  $$('.card').forEach(el=>{
    let old=before.get(el.dataset.id);
    if(groupIds.has(el.dataset.id)){el.style.visibility='hidden';newCards.push(el);return}
    if(!old||options.noAnimation)return;
    let now=el.getBoundingClientRect(),dx=old.left-now.left,dy=old.top-now.top;
    if(Math.abs(dx)+Math.abs(dy)>1)el.animate([{transform:`translate3d(${dx}px,${dy}px,0)`},{transform:'translate3d(0,0,0)'}],{duration:230,easing:'cubic-bezier(.18,.8,.22,1)'});
  });
  if(preview){
    let first=preview.ghosts[0],target=first&&newCards.find(c=>c.dataset.id===first.dataset.id);
    if(target&&newCards.length===groupIds.size){
      let a=first.getBoundingClientRect(),end=target.getBoundingClientRect(),box=preview.layer.getBoundingClientRect();
      let left=parseFloat(preview.layer.style.left)||0,top=parseFloat(preview.layer.style.top)||0,from=getComputedStyle(preview.layer).transform;
      let tx=box.left-left+end.left-a.left,ty=box.top-top+end.top-a.top;
      let anim=preview.layer.animate([{transform:from},{transform:`translate3d(${tx}px,${ty}px,0)`}],{duration:230,easing:'cubic-bezier(.18,.8,.22,1)'});
      let finish=()=>{preview.layer.remove();newCards.forEach(c=>c.style.visibility='')};
      anim.onfinish=finish;anim.oncancel=finish;
    }else{preview.layer.remove();newCards.forEach(c=>c.style.visibility='')}
  }
  $('#score').textContent=state.score;$('#undoBtn').disabled=!undo.length;save();
}
function renderK(){let h='',top='12px',tight=compactBoard();h+=pileHTML('stock',0,'5px',top)+pileHTML('waste',0,'calc(5px + var(--card-w) + 7px)',top);for(let i=0;i<4;i++)h+=pileHTML('foundation',i,pos(i+3,7),'12px',SUITS[i]);state.stock.forEach((c,i)=>{if(i===state.stock.length-1)h+=cardHTML(c,'stock',0,i,'5px',top,2)});state.waste.slice(-3).forEach((c,j,a)=>h+=cardHTML(c,'waste',0,state.waste.length-a.length+j,`calc(5px + var(--card-w) + ${7+j*10}px)`,top,3+j));state.foundations.forEach((p,i)=>p.length&&(h+=cardHTML(p.at(-1),'foundation',i,p.length-1,pos(i+3,7),top,4)));state.tableau.forEach((p,col)=>{let left=pos(col,7),base=`calc(12px + var(--card-h) + ${tight?4:16}px)`;h+=pileHTML('tableau',col,left,base);let y=0;p.forEach((c,i)=>{h+=cardHTML(c,'tableau',col,i,left,`calc(${base} + ${y}px)`,10+i);y+=c.up?(tight?17:27):(tight?9:13)})});return h}
function renderF(){let h='',tight=compactBoard();for(let i=0;i<4;i++)h+=pileHTML('cell',i,pos(i,8),'12px');for(let i=0;i<4;i++)h+=pileHTML('foundation',i,pos(i+4,8),'12px',SUITS[i]);state.cells.forEach((c,i)=>{if(c)h+=cardHTML(c,'cell',i,0,pos(i,8),'12px',4)});state.foundations.forEach((p,i)=>p.length&&(h+=cardHTML(p.at(-1),'foundation',i,p.length-1,pos(i+4,8),'12px',4)));state.tableau.forEach((p,col)=>{let left=pos(col,8),base=`calc(12px + var(--card-h) + ${tight?2:16}px)`;h+=pileHTML('tableau',col,left,base);p.forEach((c,i)=>h+=cardHTML(c,'tableau',col,i,left,`calc(${base} + ${i*(tight?19:25)}px)`,10+i))});return h}
function renderS(){let h='',tight=compactBoard();h+=pileHTML('stock',0,'5px','12px');if(state.stock.length)h+=cardHTML(state.stock.at(-1),'stock',0,state.stock.length-1,'5px','12px',3);h+=`<div style="position:absolute;right:8px;top:28px;font:12px Georgia;color:#fff9">Completed ${state.completed}/8</div>`;state.tableau.forEach((p,col)=>{let left=pos(col,10),base=`calc(12px + var(--card-h) + ${tight?7:14}px)`;h+=pileHTML('tableau',col,left,base);let y=0;p.forEach((c,i)=>{h+=cardHTML(c,'tableau',col,i,left,`calc(${base} + ${y}px)`,10+i);y+=c.up?(tight?14:22):(tight?7:11)})});return h}

function bindCards(){$$('.card').forEach(el=>{el.addEventListener('click',cardClick);el.addEventListener('pointerdown',pointerDown);el.addEventListener('contextmenu',e=>e.preventDefault())});$$('.pile').forEach(el=>el.addEventListener('click',pileClick))}
function source(el){return {kind:el.dataset.kind,pile:+el.dataset.pile,index:+el.dataset.index,id:el.dataset.id}}
function cardClick(e){e.stopPropagation();if(suppressCardClick){suppressCardClick=false;return}if(drag&&drag.moved)return;let s=source(e.currentTarget);if(s.kind==='stock'){stockClick();return}if(s.kind==='foundation'&&state.type!=='spider'){select(s);return}if(selected){if(move(selected,s.kind,s.pile))return}if(canSelect(s))select(s);else toast('That card cannot move')}
function cardById(id){let cards=[...(state.tableau||[]).flat(),...(state.stock||[]),...(state.waste||[]),...(state.foundations||[]).flat(),...(state.cells||[]).filter(Boolean)];return cards.find(c=>c.id===id)}
function showCardZoom(id){let c=cardById(id);if(!c)return;let zoom=$('#cardZoom');zoom.innerHTML=`<div class="zoom-card ${RED.includes(c.s)?'red':''}" role="img" aria-label="${label(c)} card preview"><span class="zoom-corner"><b>${RANKS[c.r-1]}</b><span>${c.s}</span></span><span class="zoom-center">${c.s}</span></div>`;zoom.classList.remove('hidden');zoom.setAttribute('aria-hidden','false')}
function hideCardZoom(){clearTimeout(zoomTimer);zoomTimer=null;$('#cardZoom').classList.add('hidden');$('#cardZoom').setAttribute('aria-hidden','true')}
function pileClick(e){if(e.target!==e.currentTarget)return;let k=e.currentTarget.dataset.kind,i=+e.currentTarget.dataset.index;if(k==='stock'){stockClick();return}if(selected)move(selected,k,i)}
function getSource(s){if(s.kind==='tableau')return state.tableau[s.pile].slice(s.index);if(s.kind==='waste')return [state.waste.at(-1)];if(s.kind==='cell')return [state.cells[s.pile]];if(s.kind==='foundation')return [state.foundations[s.pile].at(-1)];return []}
function canSelect(s){let a=getSource(s);if(!a.length||!a[0]||!a[0].up)return false;if(s.kind==='tableau'&&state.type==='spider')return a.every((c,i)=>!i||(a[i-1].r===c.r+1&&a[i-1].s===c.s));if(s.kind==='tableau'&&state.type!=='spider')return a.every((c,i)=>!i||(a[i-1].r===c.r+1&&RED.includes(a[i-1].s)!==RED.includes(c.s)));return s.index===((s.kind==='foundation'?state.foundations[s.pile]:[]).length-1)||s.kind!=='foundation'}
function select(s){selected=s;let ids=new Set(getSource(s).map(c=>c.id));$$('.card').forEach(x=>x.classList.toggle('selected',ids.has(x.dataset.id)));highlightTargets(s)}
function highlightTargets(s){$$('.pile').forEach(p=>{let k=p.dataset.kind,i=+p.dataset.index;p.classList.toggle('valid',settings.dropTargets&&legal(s,k,i))})}
function legal(s,kind,i){let cards=getSource(s),c=cards[0];if(!c)return false;if(state.type==='klondike'){if(kind==='foundation'&&cards.length===1){let p=state.foundations[i];return c.s===SUITS[i]&&c.r===(p.length? p.at(-1).r+1:1)}if(kind==='tableau'){let p=state.tableau[i],t=p.at(-1);return i!==s.pile||s.kind!=='tableau' ? (t?t.up&&t.r===c.r+1&&RED.includes(t.s)!==RED.includes(c.s):c.r===13):false}}
if(state.type==='freecell'){if(kind==='cell'&&cards.length===1)return !state.cells[i];if(kind==='foundation'&&cards.length===1){let p=state.foundations[i];return c.s===SUITS[i]&&c.r===(p.length?p.at(-1).r+1:1)}if(kind==='tableau'){let p=state.tableau[i],t=p.at(-1),free=state.cells.filter(x=>!x).length+1,empt=state.tableau.filter((x,j)=>!x.length&&j!==i).length;return i!==s.pile||s.kind!=='tableau' ? cards.length<=free*Math.pow(2,empt)&&(t?t.r===c.r+1&&RED.includes(t.s)!==RED.includes(c.s):true):false}}
if(state.type==='spider'&&kind==='tableau'){let p=state.tableau[i],t=p.at(-1);return i!==s.pile&&(t?t.r===c.r+1:true)}return false}
function take(s){let cards;if(s.kind==='tableau')cards=state.tableau[s.pile].splice(s.index);else if(s.kind==='waste')cards=[state.waste.pop()];else if(s.kind==='cell'){cards=[state.cells[s.pile]];state.cells[s.pile]=null}else if(s.kind==='foundation')cards=[state.foundations[s.pile].pop()];return cards}
function move(s,kind,i,dragPreview=null){if(!legal(s,kind,i)){toast('Not a valid move');return false}recordUndo();let cards=take(s);if(kind==='tableau')state.tableau[i].push(...cards);else if(kind==='foundation')state.foundations[i].push(...cards);else if(kind==='cell')state.cells[i]=cards[0];state.moves++;if(state.type==='klondike')state.score+=kind==='foundation'?10:s.kind==='waste'?5:0;if(state.type==='freecell'&&kind==='foundation')state.score+=10;if(state.type==='spider')state.score=Math.max(0,state.score-1);flipExposed(s);if(state.type==='spider')checkRuns();sound();render({dragPreview});checkWin();return true}
function flipExposed(s){if(s.kind==='tableau'){let p=state.tableau[s.pile],c=p.at(-1);if(c&&!c.up){c.up=true;if(state.type==='klondike')state.score+=5}}}
function stockClick(){if(state.type==='klondike'){recordUndo();if(state.stock.length){let n=state.variant==='draw3'?3:1;while(n--&&state.stock.length){let c=state.stock.pop();c.up=true;state.waste.push(c)}sound('flip')}else if(state.waste.length){state.stock=state.waste.reverse();state.stock.forEach(c=>c.up=false);state.waste=[];state.redeals++;if(state.redeals>1)state.score=Math.max(0,state.score-100)}render()}else if(state.type==='spider'){if(!state.stock.length)return;if(state.tableau.some(p=>!p.length)){toast('Fill every empty column first');return}recordUndo();for(let p of state.tableau){let c=state.stock.pop();c.up=true;p.push(c)}state.moves++;state.score=Math.max(0,state.score-1);sound('flip');for(let i=0;i<10;i++)checkRun(i);render();checkWin()}}
function checkRuns(){for(let i=0;i<10;i++)checkRun(i)}
function checkRun(i){let p=state.tableau[i];if(p.length<13)return;let a=p.slice(-13);if(a[0].r===13&&a.every((c,j)=>c.up&&c.s===a[0].s&&c.r===13-j)){p.splice(-13);state.completed++;state.score+=100;if(p.at(-1)&&!p.at(-1).up)p.at(-1).up=true;sound('win')}}
function checkWin(){let won=state.type==='spider'?state.completed===8:state.foundations.every(p=>p.length===13);if(!won)return;state.won=true;clearInterval(timerId);let key=modeKey(),list=settings.scores[key]||[];list.push({name:settings.name||'Player',score:state.score,time:state.time,date:Date.now()});list.sort((a,b)=>b.score-a.score||a.time-b.time);settings.scores[key]=list.slice(0,5);save();celebrate();setTimeout(()=>resultSheet(),900)}

function undoMove(){if(!undo.length)return;state=undo.pop();selected=null;sound();render();save()}
function hint(){let m=findMove();if(!m){toast('No obvious moves — try the stock or undo');return}let el=$(`.card[data-id="${m.id}"]`);if(el)el.classList.add('hinted');toast(m.text)}
function findMove(){if(state.type!=='spider'){let sources=[];state.tableau.forEach((p,i)=>p.length&&sources.push({kind:'tableau',pile:i,index:p.length-1,id:p.at(-1).id}));if(state.waste.length)sources.push({kind:'waste',pile:0,index:state.waste.length-1,id:state.waste.at(-1).id});if(state.cells)state.cells.forEach((c,i)=>c&&sources.push({kind:'cell',pile:i,index:0,id:c.id}));for(let s of sources)for(let i=0;i<4;i++)if(legal(s,'foundation',i))return {...s,text:`Move ${label(getSource(s)[0])} to its foundation`};for(let s of sources)for(let i=0;i<state.tableau.length;i++)if(legal(s,'tableau',i))return {...s,text:`Move ${label(getSource(s)[0])} to column ${i+1}`};if(state.stock?.length)return{id:state.stock.at(-1).id,text:'Draw from the stock'}}else{for(let x=0;x<10;x++){let p=state.tableau[x];for(let j=0;j<p.length;j++){let s={kind:'tableau',pile:x,index:j,id:p[j].id};if(canSelect(s))for(let i=0;i<10;i++)if(legal(s,'tableau',i))return{...s,text:`Move this run to column ${i+1}`}}}if(state.stock.length)return{id:state.stock.at(-1).id,text:'Deal the next row'}}return null}
async function autoFinish(){if(state.type==='spider'){toast('Complete same-suit runs from King to Ace');hint();return}let moved=0,again=true;while(again&&moved<80){again=false;let src=[];state.tableau.forEach((p,i)=>p.length&&src.push({kind:'tableau',pile:i,index:p.length-1,id:p.at(-1).id}));if(state.waste.length)src.push({kind:'waste',pile:0,index:state.waste.length-1,id:state.waste.at(-1).id});if(state.cells)state.cells.forEach((c,i)=>c&&src.push({kind:'cell',pile:i,index:0,id:c.id}));for(let s of src)for(let i=0;i<4;i++)if(legal(s,'foundation',i)){move(s,'foundation',i);moved++;again=true;await new Promise(r=>setTimeout(r,65));break}if(again)break}if(!moved)toast('No safe auto-finish moves yet')}

function nearestLegalTarget(s,x,y){let best=null;$$('.pile').forEach(p=>{let kind=p.dataset.kind,index=+p.dataset.index;if(!legal(s,kind,index))return;let top=kind==='tableau'?state.tableau[index].at(-1):kind==='foundation'?state.foundations[index].at(-1):kind==='cell'?state.cells[index]:null;let target=top?$('.card[data-id="'+top.id+'"]'):p;if(!target)return;let r=target.getBoundingClientRect(),dx=Math.max(r.left-x,0,x-r.right),dy=Math.max(r.top-y,0,y-r.bottom),distance=Math.hypot(dx,dy);if(!best||distance<best.distance)best={kind,index,distance}});let limit=Math.max(76,($('.card')?.getBoundingClientRect().width||64)*1.6);return best&&best.distance<=limit?best:null}
function startDragPreview(s){let cards=getSource(s),originals=cards.map(c=>$('.card[data-id="'+c.id+'"]')).filter(Boolean),rects=originals.map(el=>el.getBoundingClientRect()),left=Math.min(...rects.map(r=>r.left)),top=Math.min(...rects.map(r=>r.top)),layer=document.createElement('div');layer.className='drag-stack';layer.style.left=left+'px';layer.style.top=top+'px';let ghosts=originals.map((el,i)=>{let ghost=el.cloneNode(true);ghost.classList.add('drag-ghost');ghost.style.left=(rects[i].left-left)+'px';ghost.style.top=(rects[i].top-top)+'px';ghost.style.width=rects[i].width+'px';ghost.style.height=rects[i].height+'px';ghost.style.zIndex=String(i);layer.append(ghost);el.style.visibility='hidden';return ghost});document.body.append(layer);return{originals,ghosts,layer}}
function clearDragPreview(){if(!drag)return;drag.preview?.layer.remove();drag.preview?.originals.forEach(el=>el.style.visibility='');$$('.pile').forEach(p=>p.classList.remove('valid'))}
function pointerDown(e){let el=e.currentTarget;if(el.classList.contains('down'))return;let s=source(el);if(!canSelect(s))return;hideCardZoom();let startX=e.clientX,startY=e.clientY;drag={el,s,startX,startY,moved:false,zoomed:false,preview:null};zoomTimer=setTimeout(()=>{if(drag&&!drag.moved){drag.zoomed=true;showCardZoom(s.id)}},480);el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{let dx=ev.clientX-startX,dy=ev.clientY-startY;if(!drag.moved&&!drag.zoomed&&Math.abs(dx)+Math.abs(dy)>8){clearTimeout(zoomTimer);zoomTimer=null;drag.moved=true;drag.preview=startDragPreview(s);highlightTargets(s)}if(drag.moved)drag.preview.layer.style.transform=`translate3d(${dx}px,${dy}px,0)`};el.onpointerup=ev=>{el.onpointermove=el.onpointerup=el.onpointercancel=null;clearTimeout(zoomTimer);zoomTimer=null;if(drag.zoomed){hideCardZoom();suppressCardClick=true;setTimeout(()=>suppressCardClick=false,180);drag=null;return}if(drag.moved){let dx=ev.clientX-startX,dy=ev.clientY-startY;drag.preview.layer.style.transform=`translate3d(${dx}px,${dy}px,0)`;let target=nearestLegalTarget(s,ev.clientX,ev.clientY);if(target){if(!move(s,target.kind,target.index,drag.preview)){clearDragPreview();render()}}else{clearDragPreview();render()}setTimeout(()=>drag=null,0)}else drag=null};el.onpointercancel=()=>{el.onpointermove=el.onpointerup=el.onpointercancel=null;clearTimeout(zoomTimer);zoomTimer=null;hideCardZoom();if(drag?.moved){clearDragPreview();render()}drag=null}}

function openPanel(title,html,kicker='ADAM’S SOLITAIRE'){$('#panelTitle').textContent=title;$('#panelKicker').textContent=kicker;$('#panelBody').innerHTML=html;show('panel')}
function settingsPanel(){openPanel('Settings',`<div class="option"><span><b>Player</b><small style="display:block;opacity:.6">Top scores use this name</small></span><button id="changeName" class="primary">${settings.name||'Set name'}</button></div><div class="option"><b>Sound effects</b><button id="toggleSound" class="primary">${settings.sound?'On':'Off'}</button></div><div class="option"><span><b>Drop target indicators</b><small style="display:block;opacity:.6">Highlight legal places to drop cards</small></span><button id="toggleDropTargets" class="primary">${settings.dropTargets?'On':'Off'}</button></div><h3>Table color</h3><div class="theme-row">${[['green','#087144'],['blue','#075d86'],['burgundy','#842e43'],['charcoal','#394442']].map(([n,c])=>`<button class="theme-dot ${settings.theme===n?'selected':''}" data-theme="${n}" aria-label="${n}" style="background:${c}"></button>`).join('')}</div>`);$('#changeName').onclick=askName;$('#toggleSound').onclick=()=>{settings.sound=!settings.sound;save();settingsPanel()};$('#toggleDropTargets').onclick=()=>{settings.dropTargets=!settings.dropTargets;save();if(selected)highlightTargets(selected);settingsPanel()};$$('.theme-dot').forEach(b=>b.onclick=()=>{settings.theme=b.dataset.theme;document.body.dataset.theme=settings.theme;save();settingsPanel()})}
function askName(){let n=prompt('First name for Top Scores:',settings.name||'');if(n&&n.trim()){settings.name=n.trim().slice(0,20);save();settingsPanel()}}
function howPanel(){openPanel('How to Play',`<h3>Klondike</h3><p>Build tableau columns downward in alternating colors. Move Aces through Kings to the four foundations. Empty columns accept Kings.</p><h3>FreeCell</h3><p>Build downward in alternating colors and use the four free cells as temporary storage. Empty columns accept any card. Build each suit from Ace to King.</p><h3>Spider</h3><p>Build downward, regardless of suit. Only same-suit sequences move together. A complete King-to-Ace run clears automatically. Clear all eight runs to win.</p><h3>Controls</h3><p>Tap a card and then its destination, or drag it. Hold a card to see it enlarged. Use Hint, Undo, and Finish from the toolbar.</p>`)}
function scoresPanel(){let rows=Object.entries(settings.scores).flatMap(([mode,a])=>a.map(x=>({...x,mode}))).sort((a,b)=>b.score-a.score).slice(0,30);openPanel('Top Scores',rows.length?`<table class="score-table"><thead><tr><th>PLAYER</th><th>GAME</th><th>SCORE</th><th>TIME</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.mode.replaceAll('-',' · '))}</td><td>${x.score}</td><td>${fmt(x.time)}</td></tr>`).join('')}</tbody></table>`:`<div class="empty-state">🏆<h3>No scores yet</h3><p>Complete a game to claim the first spot.</p></div>`)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function menu(){openSheet('Game Menu',`<div class="sheet-list"><button id="sheetResume">Continue playing</button><button id="sheetHow">How to Play</button><button id="sheetSettings">Settings</button><button id="sheetWelcome">Save &amp; Exit to Welcome</button></div>`);$('#sheetResume').onclick=closeSheet;$('#sheetHow').onclick=()=>{closeSheet();howPanel()};$('#sheetSettings').onclick=()=>{closeSheet();settingsPanel()};$('#sheetWelcome').onclick=()=>{closeSheet();welcome()}}
function openSheet(t,h){$('#sheetTitle').textContent=t;$('#sheetBody').innerHTML=h;$('#sheet').classList.remove('hidden')}
function closeSheet(){$('#sheet').classList.add('hidden')}
function resultSheet(){openSheet('You won!',`<div style="text-align:center"><div style="font-size:54px">🏆</div><h3>${settings.name||'Player'}, brilliant game!</h3><p><b>${state.score}</b> points · <b>${fmt(state.time)}</b></p><div class="sheet-list"><button id="again">Play again</button><button id="winScores">View Top Scores</button><button id="winHome">Welcome screen</button></div></div>`);$('#again').onclick=()=>{closeSheet();setup(state.type)};$('#winScores').onclick=()=>{closeSheet();scoresPanel()};$('#winHome').onclick=()=>{closeSheet();state=null;save();welcome()}}
function celebrate(){sound('win');let c=$('#celebration'),x=c.getContext('2d'),d=devicePixelRatio;c.width=innerWidth*d;c.height=innerHeight*d;x.scale(d,d);let p=Array.from({length:90},()=>({x:Math.random()*innerWidth,y:-20-Math.random()*innerHeight*.4,v:2+Math.random()*5,r:Math.random()*6+3,c:['#f2cf69','#e44b55','#5bc9dc','#fff','#5b8cff'][Math.random()*5|0],a:Math.random()*6})),n=0;(function f(){x.clearRect(0,0,innerWidth,innerHeight);p.forEach(q=>{q.y+=q.v;q.a+=.08;x.save();x.translate(q.x,q.y);x.rotate(q.a);x.fillStyle=q.c;x.fillRect(-q.r,-q.r/2,q.r*2,q.r);x.restore()});if(n++<180)requestAnimationFrame(f);else x.clearRect(0,0,innerWidth,innerHeight)})()}

$$('.game-choice').forEach(b=>b.onclick=()=>setup(b.dataset.game));$('#variantOptions').onclick=e=>{if(e.target.dataset.v){setupVariant=e.target.dataset.v;$$('#variantOptions button').forEach(b=>b.classList.toggle('selected',b===e.target))}};$('#difficultyOptions').onclick=e=>{let b=e.target.closest('[data-d]');if(b){setupDifficulty=b.dataset.d;$$('#difficultyOptions button').forEach(x=>x.classList.toggle('selected',x===b));if(setupGame==='spider'){setupVariant={easy:'1suit',standard:'2suit',hard:'4suit'}[setupDifficulty];$$('#variantOptions button').forEach(x=>x.classList.toggle('selected',x.dataset.v===setupVariant))}}};$('#dealBtn').onclick=()=>{if(!settings.name){let n=prompt('What is your first name? (Used for Top Scores)');if(n)settings.name=n.trim().slice(0,20)}newState()};$$('[data-back]').forEach(b=>b.onclick=welcome);$('#resumeBtn').onclick=play;$('#settingsBtn').onclick=settingsPanel;$('#scoresBtn').onclick=scoresPanel;$('#howBtn').onclick=howPanel;$('#gameMenuBtn').onclick=menu;$('#soundBtn').onclick=()=>{settings.sound=!settings.sound;save();$('#soundBtn').textContent=settings.sound?'♪':'♩'};$('#undoBtn').onclick=undoMove;$('#hintBtn').onclick=hint;$('#autoBtn').onclick=autoFinish;$('#newBtn').onclick=()=>setup(state.type);$('#closeSheet').onclick=closeSheet;$('#sheet').onclick=e=>{if(e.target.id==='sheet')closeSheet()};
window.addEventListener('resize',()=>{if(state&&$('#game').classList.contains('active'))render({noAnimation:true})});
document.body.dataset.theme=settings.theme;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});welcome();
})();
